/* eslint-disable prefer-destructuring */
const VARIANT = process.env.NX_VARIANT;
const OPTIONS_PAGE_URL = process.env.PUBLIC_URL;
const UNINSTALL_URL = process.env.UNINSTALL_URL;
const FUNCTION_URL = process.env.FUNCTION_URL;
const DISCORD_CLIENT_ID = process.env.DISCORD_CLIENT_ID;
const NX_RELEASE_VERSION = process.env.NX_RELEASE_VERSION;
const MEASUREMENT_ID = process.env.MEASUREMENT_ID;
const API_SECRET = process.env.API_SECRET;
const EDGE_OAUTH_CLIENT_ID = process.env.EDGE_OAUTH_CLIENT_ID;
const FIREBASE_API_KEY = process.env.NX_FIREBASE_API_KEY;
const FIREBASE_PROJECT_ID = process.env.NX_FIREBASE_PROJECT_ID;
export { VARIANT, OPTIONS_PAGE_URL, UNINSTALL_URL, FUNCTION_URL, DISCORD_CLIENT_ID, NX_RELEASE_VERSION, MEASUREMENT_ID, API_SECRET, EDGE_OAUTH_CLIENT_ID, FIREBASE_API_KEY, FIREBASE_PROJECT_ID };
