import { REGEX_INTERVAL, REGEX_NUM } from '@apps/acf-options-page/src/util';
export const defineColumns = (t) => [
  {
    Header: t('action.initWait'),
    style: { width: '100px' },
    accessor: 'initWait',
    ariaLabel: 'initWait',
    dataType: 'number',
    list: 'interval',
    pattern: REGEX_INTERVAL,
  },
  {
    Header: t('action.name'),
    style: { width: '10%' },
    accessor: 'name',
    ariaLabel: 'name',
    autoComplete: 'off',
  },
  {
    Header: t('action.elementFinder'),
    accessor: 'elementFinder',
    ariaLabel: 'elementFinder',
    list: 'elementFinder',
    required: true,
  },
  {
    Header: t('action.value'),
    list: 'value',
    accessor: 'value',
    ariaLabel: 'value',
  },
  {
    Header: t('action.repeat'),
    style: { width: '100px' },
    accessor: 'repeat',
    ariaLabel: 'repeat',
    dataType: 'number',
    list: 'repeat',
    pattern: REGEX_NUM,
  },
  {
    Header: t('action.repeatInterval'),
    style: { width: '100px' },
    accessor: 'repeatInterval',
    ariaLabel: 'repeatInterval',
    dataType: 'number',
    list: 'interval',
    pattern: REGEX_INTERVAL,
  },
];
